FROM scratch

COPY user/k8s/faceittask /faceittask

ENV HOST=composepostgres
ENV PORT=5432
ENV USER=root
ENV PASSWORD=secret
ENV DBNAME=faceit

EXPOSE 7000
EXPOSE 7001

CMD [ "/faceittask", "--port", "7000", "--gateway_port", "7001"]